[tool.poetry]
name = "nonebot-plugin-cp-broadcast"
version = "0.1.2"
description = "A nonebot plugin"
authors = ["HuParry <huparry@outlook.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "nonebot_plugin_cp_broadcast"}]

[tool.poetry.dependencies]
python = "^3.10"
httpx = ">=0.20.0,<1.0.0"
nonebot2 = { version = "^2.0.0", extras = ["fastapi"] }
nonebot-plugin-apscheduler = "^0.3.0"
fake-useragent = "^1.1.3"
bs4 = "^0.0.1"
asyncio = "^3.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
